# Generated by Django 5.0.3 on 2024-04-06 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.TextField()),
                ('commenter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='remote_commenters', to=settings.AUTH_USER_MODEL)),
                ('proj_post', models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, related_name='remote_comments', to='SocialDistribution.projpost')),
            ],
            options={
                'ordering': ['-date_commented'],
            },
        ),
    ]
